runtime: custom
env: flex

beta_settings:
  cloud_sql_instances: maximal-radius-375114:europe-west3:prost-db=tcp:5678

handlers:
    - url: .*
      secure: always
      redirect_http_response_code: 301
      script: auto
