services:
    prost_postgres:
        container_name: "prost_postgres"
        image: postgres:15-alpine
        restart: always
        volumes:
            - ./db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "prost"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "strongpassword"

    adminer:
        image: adminer
        restart: always
        ports:
            - "8082:8080"
        environment:
            ADMINER_DEFAULT_DB_HOST: "prost_postgres"
            ADMINER_DEFAULT_DB_NAME: "prost"