spring:
    datasource:
        username: postgres
        password: ${DB_PASSWD}
        url: jdbc:postgresql://172.17.0.1:5678/prost
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 5
        tomcat:
            max-active: 5
            max-idle: 5
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: true
server:
    servlet:
        session:
            cookie:
                http-only: true
                secure: true
    forward-headers-strategy: native